name = "Aero2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9b26f2569af69f44c97d4de1bb425724cea23d6ff57c3b4c569b896c8e988c3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.240"
