#If true, players will be allowed to set their nickname to a players username. This may cause confusion in-game.
#If false, nicked players will automatically be unnicked if a player with the username joins.
allowNickToPlayerName = false
#If true, multiple players will be allowed to have the same nickname.
allowDuplicateNicknames = false
#The maximum length a nickname can be. Values above 16 may cause visual issues in-game.
# Default: 16
# Range: 1 ~ 64
nicknameMaxLength = 16
#A regex that nicknames must match to be valid. Leave empty to disable.
#For example, to only allow letters, numbers and underscores use "[a-zA-Z0-9_]*".
nicknameRegex = ""
#How names should be formatted in the different spots they may appear.
#$NICKNAME and $USERNAME are replaced by the players nickname and username respectively.
#Using both may cause visual issues in-game.
nameFormatChat = "$NICKNAME"
nameFormatTabList = "$NICKNAME ($USERNAME)"
nameFormatScoreboard = "$NICKNAME"
nameFormatNametag = "$NICKNAME"
#If true, the name formats above will also be applied to users without a nickname.
formatUnnickedUsers = false
#The length of the suffix added to NATO alphabet random names generated by /randomnick.
#For a value of 3, a generated name could be "Bravo123".
#Only applies if fetchUnusedPlayerNames is false.
# Default: 3
# Range: 1 ~ 16
natoAlphabetNamesSuffixLength = 3
#If true, the randomly generated nicknames will be unused player names fetched from the laby.net API instead of NATO alphabet names.
#This is experimental and may cause issues if the API is down or unreachable.
#As these are former real player names, some generated names may be inappropriate.
#Please use this only if necessary to avoid excessive API usage.
fetchUnusedPlayerNames = false
#If true, only admins will be able to change nicknames.
adminsOnly = false
#If true, forces clients to have Simple Nicknames installed. Without the mod, clients will only see nicknames in chat.
forceClientMod = true
#If forceClientMod is set to false, players will receive this message when they join without Simple Nicknames.
#Leave empty to disable.
modMissingMessage = "This server uses the \"§lSimple Nicknames§r\" mod for NeoForge, but you don't have it installed. Consider installing it to see nicknames in all places!"
